SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CABEZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CABEZA` (
  `PERSONA_DNI` VARCHAR(9) NOT NULL,
  `PERSONA_FAMILIA_CABEZA_DNI1` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`PERSONA_DNI`, `PERSONA_FAMILIA_CABEZA_DNI1`),
  CONSTRAINT `fk_CABEZA_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI` , `PERSONA_FAMILIA_CABEZA_DNI1`)
    REFERENCES `mydb`.`PERSONA` (`DNI` , `FAMILIA_CABEZA_DNI1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA` (
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `FAMILIA_CABEZA_DNI1` VARCHAR(9) NOT NULL,
  `CABEZA_PERSONA_DNI` VARCHAR(9) NOT NULL,
  `CABEZA_PERSONA_FAMILIA_CABEZA_DNI1` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`DNI`, `FAMILIA_CABEZA_DNI1`, `CABEZA_PERSONA_DNI`, `CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`),
  INDEX `fk_PERSONA_CABEZA1_idx` (`CABEZA_PERSONA_DNI` ASC, `CABEZA_PERSONA_FAMILIA_CABEZA_DNI1` ASC),
  CONSTRAINT `fk_PERSONA_CABEZA1`
    FOREIGN KEY (`CABEZA_PERSONA_DNI` , `CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`)
    REFERENCES `mydb`.`CABEZA` (`PERSONA_DNI` , `PERSONA_FAMILIA_CABEZA_DNI1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Municipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EDIFICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EDIFICIO` (
  `Numero` INT NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `Codigo_postal` INT NOT NULL,
  `ZONA_Nombre` VARCHAR(45) NOT NULL,
  `ZONA_Municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Numero`, `Calle`, `Codigo_postal`, `ZONA_Nombre`, `ZONA_Municipio`),
  INDEX `fk_EDIFICIO_ZONA1_idx` (`ZONA_Nombre` ASC, `ZONA_Municipio` ASC),
  CONSTRAINT `fk_EDIFICIO_ZONA1`
    FOREIGN KEY (`ZONA_Nombre` , `ZONA_Municipio`)
    REFERENCES `mydb`.`ZONA` (`Nombre` , `Municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UNIFAMILAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UNIFAMILAR` (
  `EDIFICIO_Numero` INT NOT NULL,
  `EDIFICIO_Calle` VARCHAR(45) NOT NULL,
  `EDIFICIO_Codigo_postal` INT NOT NULL,
  `EDIFICIO_ZONA_Nombre` VARCHAR(45) NOT NULL,
  `EDIFICIO_ZONA_Municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EDIFICIO_Numero`, `EDIFICIO_Calle`, `EDIFICIO_Codigo_postal`, `EDIFICIO_ZONA_Nombre`, `EDIFICIO_ZONA_Municipio`),
  CONSTRAINT `fk_UNIFAMILAR_EDIFICIO1`
    FOREIGN KEY (`EDIFICIO_Numero` , `EDIFICIO_Calle` , `EDIFICIO_Codigo_postal` , `EDIFICIO_ZONA_Nombre` , `EDIFICIO_ZONA_Municipio`)
    REFERENCES `mydb`.`EDIFICIO` (`Numero` , `Calle` , `Codigo_postal` , `ZONA_Nombre` , `ZONA_Municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BLOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BLOQUE` (
  `Nombre` VARCHAR(45) NOT NULL,
  `EDIFICIO_Numero` INT NOT NULL,
  `EDIFICIO_Calle` VARCHAR(45) NOT NULL,
  `EDIFICIO_Codigo_postal` INT NOT NULL,
  `EDIFICIO_ZONA_Nombre` VARCHAR(45) NOT NULL,
  `EDIFICIO_ZONA_Municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EDIFICIO_Numero`, `EDIFICIO_Calle`, `EDIFICIO_Codigo_postal`, `EDIFICIO_ZONA_Nombre`, `EDIFICIO_ZONA_Municipio`),
  CONSTRAINT `fk_BLOQUE_EDIFICIO1`
    FOREIGN KEY (`EDIFICIO_Numero` , `EDIFICIO_Calle` , `EDIFICIO_Codigo_postal` , `EDIFICIO_ZONA_Nombre` , `EDIFICIO_ZONA_Municipio`)
    REFERENCES `mydb`.`EDIFICIO` (`Numero` , `Calle` , `Codigo_postal` , `ZONA_Nombre` , `ZONA_Municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VIVIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIVIENDA` (
  `BLOQUE_EDIFICIO_Numero` INT NOT NULL,
  `BLOQUE_EDIFICIO_Calle` VARCHAR(45) NOT NULL,
  `BLOQUE_EDIFICIO_Codigo_postal` INT NOT NULL,
  `BLOQUE_EDIFICIO_ZONA_Nombre` VARCHAR(45) NOT NULL,
  `BLOQUE_EDIFICIO_ZONA_Municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BLOQUE_EDIFICIO_Numero`, `BLOQUE_EDIFICIO_Calle`, `BLOQUE_EDIFICIO_Codigo_postal`, `BLOQUE_EDIFICIO_ZONA_Nombre`, `BLOQUE_EDIFICIO_ZONA_Municipio`),
  CONSTRAINT `fk_VIVIENDA_BLOQUE1`
    FOREIGN KEY (`BLOQUE_EDIFICIO_Numero` , `BLOQUE_EDIFICIO_Calle` , `BLOQUE_EDIFICIO_Codigo_postal` , `BLOQUE_EDIFICIO_ZONA_Nombre` , `BLOQUE_EDIFICIO_ZONA_Municipio`)
    REFERENCES `mydb`.`BLOQUE` (`EDIFICIO_Numero` , `EDIFICIO_Calle` , `EDIFICIO_Codigo_postal` , `EDIFICIO_ZONA_Nombre` , `EDIFICIO_ZONA_Municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROPIETARIO_PISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROPIETARIO_PISO` (
  `VIVIENDA_BLOQUE_EDIFICIO_Numero` INT NOT NULL,
  `VIVIENDA_BLOQUE_EDIFICIO_Calle` VARCHAR(45) NOT NULL,
  `VIVIENDA_BLOQUE_EDIFICIO_Codigo_postal` INT NOT NULL,
  `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Nombre` VARCHAR(45) NOT NULL,
  `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Municipio` VARCHAR(45) NOT NULL,
  `PERSONA_DNI` VARCHAR(9) NOT NULL,
  `PERSONA_FAMILIA_CABEZA_DNI1` VARCHAR(9) NOT NULL,
  `PERSONA_CABEZA_PERSONA_DNI` VARCHAR(9) NOT NULL,
  `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`VIVIENDA_BLOQUE_EDIFICIO_Numero`, `VIVIENDA_BLOQUE_EDIFICIO_Calle`, `VIVIENDA_BLOQUE_EDIFICIO_Codigo_postal`, `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Nombre`, `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Municipio`, `PERSONA_DNI`, `PERSONA_FAMILIA_CABEZA_DNI1`, `PERSONA_CABEZA_PERSONA_DNI`, `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`),
  INDEX `fk_PROPIETARIO_PISO_PERSONA1_idx` (`PERSONA_DNI` ASC, `PERSONA_FAMILIA_CABEZA_DNI1` ASC, `PERSONA_CABEZA_PERSONA_DNI` ASC, `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1` ASC),
  CONSTRAINT `fk_PROPIETARIO_PISO_VIVIENDA1`
    FOREIGN KEY (`VIVIENDA_BLOQUE_EDIFICIO_Numero` , `VIVIENDA_BLOQUE_EDIFICIO_Calle` , `VIVIENDA_BLOQUE_EDIFICIO_Codigo_postal` , `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Nombre` , `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Municipio`)
    REFERENCES `mydb`.`VIVIENDA` (`BLOQUE_EDIFICIO_Numero` , `BLOQUE_EDIFICIO_Calle` , `BLOQUE_EDIFICIO_Codigo_postal` , `BLOQUE_EDIFICIO_ZONA_Nombre` , `BLOQUE_EDIFICIO_ZONA_Municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROPIETARIO_PISO_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI` , `PERSONA_FAMILIA_CABEZA_DNI1` , `PERSONA_CABEZA_PERSONA_DNI` , `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`)
    REFERENCES `mydb`.`PERSONA` (`DNI` , `FAMILIA_CABEZA_DNI1` , `CABEZA_PERSONA_DNI` , `CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROPIETARIO_UNI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROPIETARIO_UNI` (
  `PERSONA_DNI` VARCHAR(9) NOT NULL,
  `PERSONA_FAMILIA_CABEZA_DNI1` VARCHAR(9) NOT NULL,
  `PERSONA_CABEZA_PERSONA_DNI` VARCHAR(9) NOT NULL,
  `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1` VARCHAR(9) NOT NULL,
  `UNIFAMILAR_EDIFICIO_Numero` INT NOT NULL,
  `UNIFAMILAR_EDIFICIO_Calle` VARCHAR(45) NOT NULL,
  `UNIFAMILAR_EDIFICIO_Codigo_postal` INT NOT NULL,
  `UNIFAMILAR_EDIFICIO_ZONA_Nombre` VARCHAR(45) NOT NULL,
  `UNIFAMILAR_EDIFICIO_ZONA_Municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PERSONA_DNI`, `PERSONA_FAMILIA_CABEZA_DNI1`, `PERSONA_CABEZA_PERSONA_DNI`, `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`, `UNIFAMILAR_EDIFICIO_Numero`, `UNIFAMILAR_EDIFICIO_Calle`, `UNIFAMILAR_EDIFICIO_Codigo_postal`, `UNIFAMILAR_EDIFICIO_ZONA_Nombre`, `UNIFAMILAR_EDIFICIO_ZONA_Municipio`),
  INDEX `fk_PROPIETARIO_UNI_PERSONA1_idx` (`PERSONA_DNI` ASC, `PERSONA_FAMILIA_CABEZA_DNI1` ASC, `PERSONA_CABEZA_PERSONA_DNI` ASC, `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1` ASC),
  INDEX `fk_PROPIETARIO_UNI_UNIFAMILAR1_idx` (`UNIFAMILAR_EDIFICIO_Numero` ASC, `UNIFAMILAR_EDIFICIO_Calle` ASC, `UNIFAMILAR_EDIFICIO_Codigo_postal` ASC, `UNIFAMILAR_EDIFICIO_ZONA_Nombre` ASC, `UNIFAMILAR_EDIFICIO_ZONA_Municipio` ASC),
  CONSTRAINT `fk_PROPIETARIO_UNI_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI` , `PERSONA_FAMILIA_CABEZA_DNI1` , `PERSONA_CABEZA_PERSONA_DNI` , `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`)
    REFERENCES `mydb`.`PERSONA` (`DNI` , `FAMILIA_CABEZA_DNI1` , `CABEZA_PERSONA_DNI` , `CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROPIETARIO_UNI_UNIFAMILAR1`
    FOREIGN KEY (`UNIFAMILAR_EDIFICIO_Numero` , `UNIFAMILAR_EDIFICIO_Calle` , `UNIFAMILAR_EDIFICIO_Codigo_postal` , `UNIFAMILAR_EDIFICIO_ZONA_Nombre` , `UNIFAMILAR_EDIFICIO_ZONA_Municipio`)
    REFERENCES `mydb`.`UNIFAMILAR` (`EDIFICIO_Numero` , `EDIFICIO_Calle` , `EDIFICIO_Codigo_postal` , `EDIFICIO_ZONA_Nombre` , `EDIFICIO_ZONA_Municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HABITA_PISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HABITA_PISO` (
  `PERSONA_DNI` VARCHAR(9) NOT NULL,
  `PERSONA_FAMILIA_CABEZA_DNI1` VARCHAR(9) NOT NULL,
  `PERSONA_CABEZA_PERSONA_DNI` VARCHAR(9) NOT NULL,
  `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1` VARCHAR(9) NOT NULL,
  `VIVIENDA_BLOQUE_EDIFICIO_Numero` INT NOT NULL,
  `VIVIENDA_BLOQUE_EDIFICIO_Calle` VARCHAR(45) NOT NULL,
  `VIVIENDA_BLOQUE_EDIFICIO_Codigo_postal` INT NOT NULL,
  `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Nombre` VARCHAR(45) NOT NULL,
  `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PERSONA_DNI`, `PERSONA_FAMILIA_CABEZA_DNI1`, `PERSONA_CABEZA_PERSONA_DNI`, `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`, `VIVIENDA_BLOQUE_EDIFICIO_Numero`, `VIVIENDA_BLOQUE_EDIFICIO_Calle`, `VIVIENDA_BLOQUE_EDIFICIO_Codigo_postal`, `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Nombre`, `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Municipio`),
  INDEX `fk_HABITA_PISO_VIVIENDA1_idx` (`VIVIENDA_BLOQUE_EDIFICIO_Numero` ASC, `VIVIENDA_BLOQUE_EDIFICIO_Calle` ASC, `VIVIENDA_BLOQUE_EDIFICIO_Codigo_postal` ASC, `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Nombre` ASC, `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Municipio` ASC),
  CONSTRAINT `fk_HABITA_PISO_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI` , `PERSONA_FAMILIA_CABEZA_DNI1` , `PERSONA_CABEZA_PERSONA_DNI` , `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`)
    REFERENCES `mydb`.`PERSONA` (`DNI` , `FAMILIA_CABEZA_DNI1` , `CABEZA_PERSONA_DNI` , `CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HABITA_PISO_VIVIENDA1`
    FOREIGN KEY (`VIVIENDA_BLOQUE_EDIFICIO_Numero` , `VIVIENDA_BLOQUE_EDIFICIO_Calle` , `VIVIENDA_BLOQUE_EDIFICIO_Codigo_postal` , `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Nombre` , `VIVIENDA_BLOQUE_EDIFICIO_ZONA_Municipio`)
    REFERENCES `mydb`.`VIVIENDA` (`BLOQUE_EDIFICIO_Numero` , `BLOQUE_EDIFICIO_Calle` , `BLOQUE_EDIFICIO_Codigo_postal` , `BLOQUE_EDIFICIO_ZONA_Nombre` , `BLOQUE_EDIFICIO_ZONA_Municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HABITA_UNI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HABITA_UNI` (
  `UNIFAMILAR_EDIFICIO_Numero` INT NOT NULL,
  `UNIFAMILAR_EDIFICIO_Calle` VARCHAR(45) NOT NULL,
  `UNIFAMILAR_EDIFICIO_Codigo_postal` INT NOT NULL,
  `UNIFAMILAR_EDIFICIO_ZONA_Nombre` VARCHAR(45) NOT NULL,
  `UNIFAMILAR_EDIFICIO_ZONA_Municipio` VARCHAR(45) NOT NULL,
  `PERSONA_DNI` VARCHAR(9) NOT NULL,
  `PERSONA_FAMILIA_CABEZA_DNI1` VARCHAR(9) NOT NULL,
  `PERSONA_CABEZA_PERSONA_DNI` VARCHAR(9) NOT NULL,
  `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`UNIFAMILAR_EDIFICIO_Numero`, `UNIFAMILAR_EDIFICIO_Calle`, `UNIFAMILAR_EDIFICIO_Codigo_postal`, `UNIFAMILAR_EDIFICIO_ZONA_Nombre`, `UNIFAMILAR_EDIFICIO_ZONA_Municipio`, `PERSONA_DNI`, `PERSONA_FAMILIA_CABEZA_DNI1`, `PERSONA_CABEZA_PERSONA_DNI`, `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`),
  INDEX `fk_HABITA_UNI_PERSONA1_idx` (`PERSONA_DNI` ASC, `PERSONA_FAMILIA_CABEZA_DNI1` ASC, `PERSONA_CABEZA_PERSONA_DNI` ASC, `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1` ASC),
  CONSTRAINT `fk_HABITA_UNI_UNIFAMILAR1`
    FOREIGN KEY (`UNIFAMILAR_EDIFICIO_Numero` , `UNIFAMILAR_EDIFICIO_Calle` , `UNIFAMILAR_EDIFICIO_Codigo_postal` , `UNIFAMILAR_EDIFICIO_ZONA_Nombre` , `UNIFAMILAR_EDIFICIO_ZONA_Municipio`)
    REFERENCES `mydb`.`UNIFAMILAR` (`EDIFICIO_Numero` , `EDIFICIO_Calle` , `EDIFICIO_Codigo_postal` , `EDIFICIO_ZONA_Nombre` , `EDIFICIO_ZONA_Municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HABITA_UNI_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI` , `PERSONA_FAMILIA_CABEZA_DNI1` , `PERSONA_CABEZA_PERSONA_DNI` , `PERSONA_CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`)
    REFERENCES `mydb`.`PERSONA` (`DNI` , `FAMILIA_CABEZA_DNI1` , `CABEZA_PERSONA_DNI` , `CABEZA_PERSONA_FAMILIA_CABEZA_DNI1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
