-- MySQL Script generated by MySQL Workbench
-- 12/09/16 17:11:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema regalos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema regalos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `regalos` DEFAULT CHARACTER SET utf8 ;
USE `regalos` ;

-- -----------------------------------------------------
-- Table `regalos`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regalos`.`CLIENTE` (
  `Codigo_cliente` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  PRIMARY KEY (`Codigo_cliente`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC));


-- -----------------------------------------------------
-- Table `regalos`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regalos`.`CATEGORIA` (
  `Identificador` INT NOT NULL AUTO_INCREMENT,
  `Breve_descripcion` TIMESTAMP NOT NULL,
  `Nombre_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Identificador`));


-- -----------------------------------------------------
-- Table `regalos`.`REGALO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regalos`.`REGALO` (
  `Numero_referencia` INT NOT NULL AUTO_INCREMENT,
  `Cantidad_articulo` INT NOT NULL,
  `Precio_unidad` INT NOT NULL,
  `CATEGORIA_Identificador` INT NOT NULL,
  PRIMARY KEY (`Numero_referencia`),
  INDEX `fk_REGALO_CATEGORIA1_idx` (`CATEGORIA_Identificador` ASC),
  CONSTRAINT `fk_REGALO_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_Identificador`)
    REFERENCES `regalos`.`CATEGORIA` (`Identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `regalos`.`RECIBE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regalos`.`RECIBE` (
  `Dia` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Dedicatoria` VARCHAR(45) NOT NULL,
  `REGALO_Numero_referencia` INT NOT NULL,
  PRIMARY KEY (`Dia`, `REGALO_Numero_referencia`),
  INDEX `fk_RECIBE_REGALO1_idx` (`REGALO_Numero_referencia` ASC),
  CONSTRAINT `fk_RECIBE_REGALO1`
    FOREIGN KEY (`REGALO_Numero_referencia`)
    REFERENCES `regalos`.`REGALO` (`Numero_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `regalos`.`PREFERENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regalos`.`PREFERENCIA` (
  `REGALO_Numero_referencia` INT NOT NULL,
  `REGALO_CATEGORIA_Identificador` INT NOT NULL,
  PRIMARY KEY (`REGALO_Numero_referencia`, `REGALO_CATEGORIA_Identificador`));


-- -----------------------------------------------------
-- Table `regalos`.`RECEPTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regalos`.`RECEPTOR` (
  `Id_regalo` INT NOT NULL,
  `Nombre` VARCHAR(30) NULL DEFAULT CURRENT_TIMESTAMP,
  `Apellido` VARCHAR(30) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Codigo_postal` INT NULL,
  `Provincia` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `RECIBE_Dia` DATE NOT NULL,
  `RECIBE_REGALO_Numero_referencia` INT NOT NULL,
  `PREFERENCIA_REGALO_Numero_referencia` INT NOT NULL,
  `PREFERENCIA_REGALO_CATEGORIA_Identificador` INT NOT NULL,
  INDEX `fk_RECEPTOR_RECIBE1_idx` (`RECIBE_Dia` ASC, `RECIBE_REGALO_Numero_referencia` ASC),
  INDEX `fk_RECEPTOR_PREFERENCIA1_idx` (`PREFERENCIA_REGALO_Numero_referencia` ASC, `PREFERENCIA_REGALO_CATEGORIA_Identificador` ASC),
  PRIMARY KEY (`Id_regalo`),
  CONSTRAINT `fk_RECEPTOR_RECIBE1`
    FOREIGN KEY (`RECIBE_Dia` , `RECIBE_REGALO_Numero_referencia`)
    REFERENCES `regalos`.`RECIBE` (`Dia` , `REGALO_Numero_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECEPTOR_PREFERENCIA1`
    FOREIGN KEY (`PREFERENCIA_REGALO_Numero_referencia` , `PREFERENCIA_REGALO_CATEGORIA_Identificador`)
    REFERENCES `regalos`.`PREFERENCIA` (`REGALO_Numero_referencia` , `REGALO_CATEGORIA_Identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `regalos`.`REGALA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regalos`.`REGALA` (
  `CLIENTE_Codigo_cliente` INT NOT NULL,
  `RECEPTOR_Id_regalo` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_Codigo_cliente`),
  INDEX `fk_REGALA_RECEPTOR1_idx` (`RECEPTOR_Id_regalo` ASC),
  CONSTRAINT `fk_REGALA_CLIENTE1`
    FOREIGN KEY (`CLIENTE_Codigo_cliente`)
    REFERENCES `regalos`.`CLIENTE` (`Codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REGALA_RECEPTOR1`
    FOREIGN KEY (`RECEPTOR_Id_regalo`)
    REFERENCES `regalos`.`RECEPTOR` (`Id_regalo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
