USE regalos;
DELIMITER $$
DROP TRIGGER IF EXISTS precioTotal;
CREATE TRIGGER precioTotal before insert on REGALO
FOR EACH ROW
BEGIN 
ALTER TABLE REGALO ADD Precio_Total FLOAT NOT NULL 
END $$
DELIMITER;