-- MySQL Script generated by MySQL Workbench
-- 12/21/16 13:07:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BaseLandyDatosPedro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BaseLandyDatosPedro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BaseLandyDatosPedro` DEFAULT CHARACTER SET utf8 ;
USE `BaseLandyDatosPedro` ;

-- -----------------------------------------------------
-- Table `BaseLandyDatosPedro`.`UsuarioDeClaseAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseLandyDatosPedro`.`UsuarioDeClaseAdmin` (
  `Id_usuario` INT NOT NULL AUTO_INCREMENT,
  `AdminBaseDatosUsuario` VARCHAR(45) NOT NULL,
  `DatosBaseAdminPasswd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_usuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
