-- MySQL Script generated by MySQL Workbench
-- 11/23/16 10:17:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA` (
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Municipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EDIFICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EDIFICIO` (
  `Id_edificio` INT NOT NULL AUTO_INCREMENT,
  `Numero` INT NOT NULL,
  `CodigoPostal` INT NOT NULL,
  `ZONA_Nombre` VARCHAR(45) NOT NULL,
  `ZONA_Municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_edificio`, `Numero`, `CodigoPostal`, `ZONA_Nombre`, `ZONA_Municipio`),
  INDEX `fk_EDIFICIO_ZONA1_idx` (`ZONA_Nombre` ASC, `ZONA_Municipio` ASC),
  CONSTRAINT `fk_EDIFICIO_ZONA1`
    FOREIGN KEY (`ZONA_Nombre` , `ZONA_Municipio`)
    REFERENCES `mydb`.`ZONA` (`Nombre` , `Municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UNIFAMILAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UNIFAMILAR` (
  `EDIFICIO_Id_edificio` INT NOT NULL,
  INDEX `fk_UNIFAMILAR_EDIFICIO_idx` (`EDIFICIO_Id_edificio` ASC),
  PRIMARY KEY (`EDIFICIO_Id_edificio`),
  CONSTRAINT `fk_UNIFAMILAR_EDIFICIO`
    FOREIGN KEY (`EDIFICIO_Id_edificio`)
    REFERENCES `mydb`.`EDIFICIO` (`Id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BLOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BLOQUE` (
  `EDIFICIO_Id_edificio` INT NOT NULL,
  `Letra` VARCHAR(1) NOT NULL,
  INDEX `fk_BLOQUE_EDIFICIO1_idx` (`EDIFICIO_Id_edificio` ASC),
  PRIMARY KEY (`EDIFICIO_Id_edificio`),
  CONSTRAINT `fk_BLOQUE_EDIFICIO1`
    FOREIGN KEY (`EDIFICIO_Id_edificio`)
    REFERENCES `mydb`.`EDIFICIO` (`Id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VIVIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIVIENDA` (
  `BLOQUE_EDIFICIO_Id_edificio` INT NOT NULL,
  PRIMARY KEY (`BLOQUE_EDIFICIO_Id_edificio`),
  CONSTRAINT `fk_VIVIENDA_BLOQUE1`
    FOREIGN KEY (`BLOQUE_EDIFICIO_Id_edificio`)
    REFERENCES `mydb`.`BLOQUE` (`EDIFICIO_Id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CABEZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CABEZA` (
  `PERSONA_DNI1` VARCHAR(9) NOT NULL,
  `PERSONA_DNI` VARCHAR(9) NOT NULL,
  INDEX `fk_CABEZA_PERSONA2_idx` (`PERSONA_DNI1` ASC),
  PRIMARY KEY (`PERSONA_DNI`),
  CONSTRAINT `fk_CABEZA_PERSONA2`
    FOREIGN KEY (`PERSONA_DNI1`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CABEZA_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROPIETARIO_BL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROPIETARIO_BL` (
  `PERSONA_DNI` VARCHAR(9) NOT NULL,
  `VIVIENDA_BLOQUE_EDIFICIO_Id_edificio` INT NOT NULL,
  PRIMARY KEY (`PERSONA_DNI`),
  INDEX `fk_PROPIETARIO_BL_PERSONA1_idx` (`PERSONA_DNI` ASC),
  INDEX `fk_PROPIETARIO_BL_VIVIENDA1_idx` (`VIVIENDA_BLOQUE_EDIFICIO_Id_edificio` ASC),
  CONSTRAINT `fk_PROPIETARIO_BL_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROPIETARIO_BL_VIVIENDA1`
    FOREIGN KEY (`VIVIENDA_BLOQUE_EDIFICIO_Id_edificio`)
    REFERENCES `mydb`.`VIVIENDA` (`BLOQUE_EDIFICIO_Id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROPIETARIO_UNI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROPIETARIO_UNI` (
  `PERSONA_DNI` VARCHAR(9) NOT NULL,
  `UNIFAMILAR_EDIFICIO_Id_edificio` INT NOT NULL,
  PRIMARY KEY (`PERSONA_DNI`),
  INDEX `fk_PROPIETARIO_UNI_PERSONA1_idx` (`PERSONA_DNI` ASC),
  INDEX `fk_PROPIETARIO_UNI_UNIFAMILAR1_idx` (`UNIFAMILAR_EDIFICIO_Id_edificio` ASC),
  CONSTRAINT `fk_PROPIETARIO_UNI_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROPIETARIO_UNI_UNIFAMILAR1`
    FOREIGN KEY (`UNIFAMILAR_EDIFICIO_Id_edificio`)
    REFERENCES `mydb`.`UNIFAMILAR` (`EDIFICIO_Id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VIVE_BL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIVE_BL` (
  `VIVIENDA_BLOQUE_EDIFICIO_Id_edificio` INT NOT NULL,
  `PERSONA_DNI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`VIVIENDA_BLOQUE_EDIFICIO_Id_edificio`),
  INDEX `fk_VIVE_BL_PERSONA1_idx` (`PERSONA_DNI` ASC),
  CONSTRAINT `fk_VIVE_BL_VIVIENDA1`
    FOREIGN KEY (`VIVIENDA_BLOQUE_EDIFICIO_Id_edificio`)
    REFERENCES `mydb`.`VIVIENDA` (`BLOQUE_EDIFICIO_Id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIVE_BL_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VIVE_UNI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIVE_UNI` (
  `UNIFAMILAR_EDIFICIO_Id_edificio` INT NOT NULL,
  `PERSONA_DNI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`UNIFAMILAR_EDIFICIO_Id_edificio`),
  INDEX `fk_VIVE_UNI_PERSONA1_idx` (`PERSONA_DNI` ASC),
  CONSTRAINT `fk_VIVE_UNI_UNIFAMILAR1`
    FOREIGN KEY (`UNIFAMILAR_EDIFICIO_Id_edificio`)
    REFERENCES `mydb`.`UNIFAMILAR` (`EDIFICIO_Id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIVE_UNI_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
