-- MySQL Script generated by MySQL Workbench
-- 12/18/16 13:50:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdpeliculas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdpeliculas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdpeliculas` DEFAULT CHARACTER SET utf8 ;
USE `bdpeliculas` ;

-- -----------------------------------------------------
-- Table `bdpeliculas`.`Pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdpeliculas`.`Pelicula` (
  `Id_pelicula` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Director` VARCHAR(70) NULL,
  PRIMARY KEY (`Id_pelicula`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
